# FDO_DISTRIBUTION_TAG is the tag of the docker image used for the build
# jobs. If the image doesn't exist yet, the docker-image stage generates it
# or copies it from upstream (this is all handled by the templates).
#
# In order to generate a new image, one should generally change the tag.
# While removing the image from the registry would also work, that's not
# recommended except for ephemeral images during development: Replacing an
# image after a significant amount of time might pull in newer versions of
# gcc/clang or other packages, which might break the build with older commits
# using the same tag.
#
variables:
  FDO_UPSTREAM_REPO: xorg/driver/xf86-video-amdgpu

include:
  - project: 'freedesktop/ci-templates'
    ref: 9568e38927f9e9c48d4f586f84a071c3a4bdcd39
    file: '/templates/debian.yml'
  - template: Security/SAST.gitlab-ci.yml

stages:
  - docker-image
  - build
  - test

.debian-testing:
  variables:
    FDO_DISTRIBUTION_VERSION: bookworm-slim
    FDO_DISTRIBUTION_EXEC: 'bash .gitlab-ci/debian-install.sh'
    FDO_DISTRIBUTION_PACKAGES: 'ca-certificates'
    FDO_DISTRIBUTION_TAG: "2024-07-12-ci-deb-repo"
    PKG_REPO_REV: "bca9635d"

container-build:
  extends:
    - .debian-testing
    - .fdo.container-build@debian
  stage: docker-image

# The default build instructions
.default_build:
  extends:
    - .debian-testing
    - .fdo.distribution-image@debian
  stage: build
  script:
  - ./autogen.sh
  - make -j$(nproc) check V=1
  - make install V=1
  - make -j$(nproc) distcheck
  variables:
    CFLAGS: "-pipe -g -O2 -Werror"
    ACLOCAL_PATH: /usr/local/xserver-$XSERVER_VERSION/share/aclocal
    PKG_CONFIG_PATH: /usr/local/xserver-$XSERVER_VERSION/lib/pkgconfig

linux:
  extends: .default_build
  parallel:
    matrix:
      - XSERVER_VERSION: ["1.18", "1.19", "1.20", "21.1"]

linux-clang:
  extends: linux
  variables:
    CC: clang
